### PR TITLE
Add support for dynamic input data

### PR DESCRIPTION
**Pull request by ryanwoodcox**
Implemented OnChanges to support re-initliazing the component when input properties change.
Reference to issue: https://github.com/bonjurmrfirst/angular4-carousel/issues/14

### CODE REVIEW

**Comment by dockleryxk** [comment]
closes #14

**Comment by bonjurmrfirst** [comment]
Hi,
dynamic input data breaks carousel, so I reverted changes.
Please let me know if I wrong, but after adding OnChanges, carousel not work properly (images sliding on hover, delay different for images)

**Comment by ryanwoodcox** [comment]
Is that not something you can fix by reworking the styles? I've done a lot of reworking of the styles to meet my needs, so I am not experiencing this issue.

**Comment by bonjurmrfirst** [comment]
Moving carousel initialization from OnInit to OnChanges will not work, we should also reset timers and other data related to current carousel instance.

Here is solution works for me to change configs in run-time:

1. HTML: add *ngIf="enabled" to carousel component. Let enabled variable to be true by default.
```
<carousel *ngIf="enabled" [sources]="imageSources" [config]="config"></carousel>
```

2. TS: add function that will be reset carousel with new config and/or images.

```
public enabled = true;

changeConfig() {
    this.enabled = false;

    setTimeout(() => {
      this.imageSources = [
         // new images
      ]

      this.config = {
        // new config
      };

      this.enabled = true;
    });
  }
```

**Pull request merged**
